#include "priority.h"

int main() {
    PriorityQueue* pq = createQueue();
    int choice;
    char data[MAX_DATA_LENGTH];
    int priority, count;

    srand(time(NULL));

    while (1) {
        
        printf("\nМеню:\n");
        printf("1. Добавить элемент\n");
        printf("2. Извлечь элемент с наивысшим приоритетом\n");
        printf("3. Извлечь элемент с указанным приоритетом\n");
        printf("4. Извлечь элемент с приоритетом не ниже указанного\n");
        printf("5. Показать очередь\n");
        printf("6. Автогенерация элементов\n");
        printf("7. Удалить элемент с указанным приоритетом\n");
        printf("0. Выйти\n");
        printf("Ваш выбор: ");
        scanf("%d", &choice);

        switch (choice) {
            case 1:
                printf("Введите данные (строка): ");
                scanf(" %[^\n]", data);
                printf("Введите приоритет (0-255): ");
                scanf("%d", &priority);
                enqueue(pq, data, priority);  // Добавление элемента
                printf("Элемент добавлен.\n");
                break;
            case 2:
                dequeue(pq);  // Извлечение элемента с наивысшим приоритетом
                break;
            case 3:
                printf("Введите приоритет для извлечения: ");
                scanf("%d", &priority);
                dequeueWithPriority(pq, priority);  // Извлечение элемента с указанным приоритетом
                break;
            case 4:
                printf("Введите минимальный приоритет для извлечения: ");
                scanf("%d", &priority);
                dequeueWithMinPriority(pq, priority);  // Извлечение элемента с приоритетом не ниже указанного
                break;
            case 5:
                printf("Текущая очередь:\n");
                printQueue(pq);  // Печать всей очереди
                break;
            case 6:
                printf("Введите количество элементов для генерации: ");
                scanf("%d", &count);
                autoGenerateData(pq, count);  // Автоматическая генерация элементов
                break;
            case 7:
                printf("Введите приоритет для удаления: ");
                scanf("%d", &priority);
                deleteNodeWithPriority(pq, priority);  // Удаление элемента с указанным приоритетом
                break;
            case 0:
                printf("Выход из программы.\n");
                deleteQueue(pq);  // Освобождение памяти перед выходом
                return 0;
            default:
                printf("Неверный выбор. Пожалуйста, попробуйте снова.\n");
                break;
        }
    }
}
